### ISSUE TITLE
[Urgent ]We are getting issue while tryikng to initialise PlayConfigContext

### ISSUE THREAD

**Issue by Amit-1992** [honeybadger-io/honeybadger-java#60] opened 2018-09-04 12:43 UTC
Getting error,

 play.Configuration cannot be converted to com.typesafe.config.Config
11:23:24.103 [error]         ConfigContext context = new PlayConfigContext(configuration, environment);

Here configuration is an object of play.config. Same was working before.now, its failing and is expecting constructor to have argument of type "com.typesafe.config.Config".

Did you make any upgradations which are not compatible.

Entry in build.sdt is:
libraryDependencies += "io.honeybadger" % "honeybadger-java" % "]1,)"

Please help ASAP as most of the links in document "Readme.md" are also throwing 404

**Comment by joshuap** [comment] 2018-09-04 14:52
Sorry for the trouble, it’s possible there was a breaking change in 2.0.0. We will look into this (and will also update the broken links in the readme).

In the meantime, you should lock the version you’re depending on to 1.1.0, which is the previous version before the latest 2.0.0 release.

**Comment by Amit-1992** [comment] 2018-09-05 04:39
2.5.2

**Comment by JasonTrue** [comment] 2018-09-05 04:54
Can you tell me if this reproduces with the following?

```
libraryDependencies += "io.honeybadger" % "honeybadger-java" % "2.0.0"
```

You appear to be referencing a 1.x build.

**Comment by Amit-1992** [comment] 2018-09-05 05:11
I was checking the dependency it downloads with 
libraryDependencies += "io.honeybadger" % "honeybadger-java" % "]1,)"

It was honeybadger-java (2.x.x) [latest build]. Issue persisted.

Then we added, dependencyOverride for version 1.1.0 and compilation errors were gone and project was up again.

What I could see was that arguments for constructor of class PlayConfigContext have changes in latest version(2.x.x). Thus, code is not compiling. Although it still accepts2 parameters : configuration and environment but, data type of configuration has changed.

**Comment by JasonTrue** [comment] 2018-09-05 05:40
Oh, right, I was reading it wrong. It should translate to a version >=1.0. I think you could change it to ```libraryDependencies += "io.honeybadger" % "honeybadger-java" % "]1.0,2.0["``` for now while I investigate further. I'm not sure why this doesn't reproduce on our crywolf example so I'll have to do some digging.

**Comment by JasonTrue** [comment] 2018-09-07 01:31
@Amit-1992 can you tell me how you're plugging in the error handler? In our sample Play app for Play 2.6 we simply add a couple of lines to `conf/application.conf` like this:

play.http.errorHandler = io.honeybadger.reporter.play.HoneybadgerErrorHandler
honeybadger.api_key = [ourapikey]

If your integration is more complex than this, it might help to understand how you instantiate the error handler. Or if you're using anything unusual for configuration management.

I'd like to figure out a way to reproduce the issue, but it doesn't happen for me.

**Comment by Amit-1992** [comment] 2018-09-07 05:44
Hi,

We are including the library in our project using following entry in **build.sbt**
libraryDependencies += "io.honeybadger" % "honeybadger-java" % "1.1.0"

Then we are configuring it using following entry in **production.conf**. This is environment specific file for application.conf in our codebase.
honeybadger.api_key = [our key]
play.http.errorHandler = lib.honeybadger.HoneybadgerErrorHandler

**Comment by joshuap** [comment] 2019-05-10 22:22
Closing this since there hasn't been activity in a while. Feel free to comment back here with the requested info/reopen if it's still an issue. Thanks!

**Closed by joshuap** 2019-05-10 22:22 UTC
